sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
env:
  - USE_LOCK=0
  - USE_LOCK=1
matrix:
  allow_failures:
    - env: USE_LOCK=0
  fast_finish: true

cache:
  directories:
    - vendor

before_script:
  - "[ $USE_LOCK -eq 0 ] || rm composer.lock"
  - composer self-update
  - composer install

script:
  - composer test
  - composer acceptance
